create table dec01 (
	id integer generated by default as identity,
	calories text
);

\COPY dec01 (calories) FROM input_01.txt NULL '';

-- How many rows are there including NULL rows?
select count(*) from dec01;

-- what does this look like once imported?
select * from dec01
order by id;

-- My complicated solution using lots of string/array functionality
with cals as (
	select *, row_number() over (order by a) elf from (
		select unnest(
			STRING_TO_ARRAY(
				string_agg(COALESCE(calories,'|'),','),',|,'
			)
		) a
	from dec01
  )b
)
select elf, sum(t::int) c from cals, string_to_table(a,',') as t
group by cals.elf
order by 2 desc;


-- Taking inspiration from Feike Steenbergen 
-- https://gitlab.com/feike/adventofcode/-/blob/master/2022/day01/01-1.sql

-- Star 1
WITH inventory AS (
    SELECT
        nullif(calories, '')::bigint AS calories,
        count(*) FILTER (WHERE calories is null) OVER (ORDER BY id) AS elf,
        id
    FROM
        dec01
)
SELECT sum(calories) as c
	FROM inventory
	GROUP BY elf
	ORDER BY 1 desc;


-- Star 2
WITH inventory AS (
    SELECT
        nullif(calories, '')::bigint AS calories,
        count(*) FILTER (WHERE calories is null) OVER (ORDER BY id) AS elf,
        id
    FROM
        dec01
)
select sum(c) from ( 
	SELECT sum(calories) as c
		FROM inventory
		GROUP BY elf
		ORDER BY 1 desc
		limit 3
) x;