create table dec03 (
	id integer generated by default as identity,
	contents text
);

-- COPY the text into the appropriate columns
\COPY dec03 (contents) FROM input_03.txt NULL '';

-- how many rows and what does it look like?
select count(*) from dec03;
select * from dec03;

-- Start by splitting the string apart appropriately.
with rucksack as (
	select id, 
		substring(contents,1,length(contents)/2) sack1, 
		substring(contents,length(contents)/2+1) sack2
	from dec03
),
contents1 as (
	select id, string_to_table(sack1,null) as item from rucksack 
),
contents2 as (
	select id, string_to_table(sack2,null) as item from rucksack
)
select sum(position(item in'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')) total_priority
from (
	select * from contents1
	intersect distinct
	select * from contents2
) y;

--Alternative using INTERSECT DISTINCT
--select sum(position(item in'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')) total_priority
from (
	select * from contents1
	intersect distinct
	select * from contents2
) y;

-- Star2
with rucksack as (
	select id, 
		   contents,
		   (id-1)/3 as elf_group
		   ,mod(id-1,3) as elf
	from dec03
)
select * from rucksack;

-- Now how can I use this info?
with rucksack as (
	select id, 
		   contents,
		   (id-1)/3 as elf_group,
		   mod(id-1,3) as elf
	from dec03
),
contents as ( 
	select string_to_table(contents,null) item, elf_group, elf
	from rucksack
)
select sum(position(item in'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')) total_priority
from (
	select item, elf_group
	from contents where elf = 0
	
	intersect distinct
	
	select item, elf_group
	from contents where elf = 1
	
	intersect distinct 
	
	select item, elf_group
	from contents where elf = 2
) x;


contents1 as (
	select id, string_to_table(sack1,null) as item from rucksack 
),
contents2 as (
	select id, string_to_table(sack2,null) as item from rucksack
)
select sum(position(item in'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')) total_priority
from (
	select * from contents1
	intersect distinct
	select * from contents2
) y;