create table dec02 (
	id integer generated by default as identity,
	opp text,
	play text
);

-- COPY the text into the appropriate columns
\COPY dec02 (opp, play) FROM input_02.txt NULL '' DELIMITER ' ';

-- how many rows and what does the data look like?
SELECT count(*) from dec02;
SELECT * from dec02;

-- Star 1
WITH guess_matrix AS (
	select * from (VALUES 
					('A','X',4), ('A','Y',8),('A','Z',3), -- Opponent ROCK
					('B','X',1), ('B','Y',5),('B','Z',9), -- Opponent PAPER
					('C','X',7), ('C','Y',2),('C','Z',6) -- Opponent SCISSORS					
	) as t(opp, play, points)
)
select sum(points) from guess_matrix gm
inner join dec02 d using (opp, play);


-- Star 2
WITH guess_matrix AS (
	select * from (VALUES 
					('A','X',3), ('B','X',1),('C','X',2), -- Opponent LOSE
					('A','Y',4), ('B','Y',5),('C','Y',6), -- Opponent DRAW
					('A','Z',8), ('B','Z',9),('C','Z',7) -- Opponent WIN					
	) as t(opp, play, points)
)
select sum(points) from guess_matrix gm
inner join dec02 d using (opp, play);
